// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAciY0oiIUQ-EiGwf5zKBQ_YgkO-2AKgHQ',
    appId: '1:74780698782:web:141881b92b1032dfa4f38f',
    messagingSenderId: '74780698782',
    projectId: 'quillquest-cdbf5',
    authDomain: 'quillquest-cdbf5.firebaseapp.com',
    storageBucket: 'quillquest-cdbf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMKeJlQlukzlrrSfCO3mkgoZau6dKE85A',
    appId: '1:74780698782:android:9dc18afcf7ae90b2a4f38f',
    messagingSenderId: '74780698782',
    projectId: 'quillquest-cdbf5',
    storageBucket: 'quillquest-cdbf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRqWm4lbD1VVQGs2EDYCFhkZ9-jTFwGb4',
    appId: '1:74780698782:ios:2acd6edd9b20e51ea4f38f',
    messagingSenderId: '74780698782',
    projectId: 'quillquest-cdbf5',
    storageBucket: 'quillquest-cdbf5.firebasestorage.app',
    iosBundleId: 'com.example.quillQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRqWm4lbD1VVQGs2EDYCFhkZ9-jTFwGb4',
    appId: '1:74780698782:ios:2acd6edd9b20e51ea4f38f',
    messagingSenderId: '74780698782',
    projectId: 'quillquest-cdbf5',
    storageBucket: 'quillquest-cdbf5.firebasestorage.app',
    iosBundleId: 'com.example.quillQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAciY0oiIUQ-EiGwf5zKBQ_YgkO-2AKgHQ',
    appId: '1:74780698782:web:5c29f1751deef113a4f38f',
    messagingSenderId: '74780698782',
    projectId: 'quillquest-cdbf5',
    authDomain: 'quillquest-cdbf5.firebaseapp.com',
    storageBucket: 'quillquest-cdbf5.firebasestorage.app',
  );

}